import React, { useState, useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { Button } from "../components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../components/ui/card"
import { Badge } from "../components/ui/badge"
import { Navigation } from "../components/navigation"
import { Sparkles, Brain, Target, TrendingUp, BookOpen, ChevronRight, AlertTriangle, CheckCircle2, FileText } from "lucide-react"

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000"

export default function GeminiReportPage() {
  const navigate = useNavigate()
  const [reportData, setReportData] = useState(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    const fetchAggregateData = async () => {
      try {
        const token = localStorage.getItem("token")
        if (!token) {
          navigate("/auth")
          return
        }

        // We fetch the dashboard summary which contains aggregated stats across ALL tests
        const res = await fetch(`${API_URL}/api/dashboard/summary`, {
          headers: { Authorization: `Bearer ${token}` },
        })
        const data = await res.json()

        if (data.success && data.summary) {
          setReportData(data.summary)
        }
      } catch (err) {
        console.error("Error fetching Gemini report data:", err)
      } finally {
        setIsLoading(false)
      }
    }

    fetchAggregateData()
  }, [navigate])

  if (isLoading) {
    return (
      <div className="min-h-screen bg-slate-50 font-sans flex flex-col">
        <Navigation />
        <div className="flex-1 flex items-center justify-center pt-20">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto mb-4"></div>
            <p className="text-lg text-slate-500 font-medium">Gemini is analyzing your historical data...</p>
          </div>
        </div>
      </div>
    )
  }

  if (!reportData || reportData.totalAssessments === 0) {
    return (
      <div className="min-h-screen bg-slate-50 font-sans flex flex-col">
        <Navigation />
        <div className="flex-1 flex items-center justify-center px-4 pt-20">
          <Card className="max-w-md w-full bg-white border-slate-200 shadow-xl rounded-2xl text-center p-6">
            <div className="w-16 h-16 bg-purple-50 rounded-full flex items-center justify-center mx-auto mb-4 border border-purple-100">
              <Sparkles className="h-8 w-8 text-purple-500" />
            </div>
            <h2 className="text-2xl font-bold text-slate-900 mb-2">Insufficient Data</h2>
            <p className="text-slate-500 font-medium mb-6">
              Gemini needs at least one completed assessment to generate a comprehensive behavioral and cognitive report.
            </p>
            <Button onClick={() => navigate("/")} className="w-full bg-purple-600 hover:bg-purple-700 text-white rounded-xl shadow-md">
              Take an Assessment
            </Button>
          </Card>
        </div>
      </div>
    )
  }

  // Derive Strengths and Weaknesses from aggregate topic stats
  const topicEntries = Object.entries(reportData.topicStats || {}).sort(([, a], [, b]) => b.accuracy - a.accuracy)
  const strengths = topicEntries.filter(([, data]) => data.accuracy >= 70).slice(0, 3)
  const weaknesses = topicEntries.filter(([, data]) => data.accuracy < 60).slice(0, 3)

  return (
    <div className="min-h-screen bg-slate-50 font-sans flex flex-col">
      <Navigation />
      
      <div className="pt-24 pb-12 flex-1 relative z-0">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          
          {/* Header Section */}
          <div className="mb-10 text-center">
            <Badge className="bg-purple-100 text-purple-700 border-purple-200 px-4 py-1.5 font-bold tracking-wide text-xs mb-4 shadow-sm">
              <Sparkles className="w-3.5 h-3.5 mr-1.5" /> GEMINI AI ANALYSIS
            </Badge>
            <h1 className="text-3xl md:text-5xl font-bold text-slate-900 mb-4 tracking-tight">
              Comprehensive Cognitive Profile
            </h1>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto font-medium">
              A holistic evaluation of your aptitude patterns across {reportData.totalAssessments} completed assessments, generated by Gemini 2.5 Pro.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <Card className="bg-white border border-slate-200 shadow-sm rounded-2xl p-6 flex flex-col justify-center items-center text-center">
              <Brain className="h-8 w-8 text-purple-600 mb-3" />
              <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Global Accuracy</p>
              <h3 className="text-4xl font-bold text-slate-900">{reportData.averageScore}%</h3>
            </Card>
            <Card className="bg-white border border-slate-200 shadow-sm rounded-2xl p-6 flex flex-col justify-center items-center text-center">
              <TrendingUp className="h-8 w-8 text-blue-600 mb-3" />
              <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Current Trajectory</p>
              <h3 className="text-2xl font-bold text-slate-900 capitalize">{reportData.trend || "Establishing..."}</h3>
            </Card>
            <Card className="bg-white border border-slate-200 shadow-sm rounded-2xl p-6 flex flex-col justify-center items-center text-center">
              <Target className="h-8 w-8 text-emerald-600 mb-3" />
              <p className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Peak Difficulty</p>
              <h3 className="text-2xl font-bold text-slate-900 capitalize">{reportData.bestDifficulty || "N/A"}</h3>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
            {/* Core Strengths */}
            <Card className="bg-white border border-slate-200 shadow-sm rounded-2xl">
              <CardHeader className="border-b border-slate-100 pb-4">
                <CardTitle className="flex items-center gap-2 text-emerald-800">
                  <CheckCircle2 className="h-5 w-5 text-emerald-600" /> Confirmed Strengths
                </CardTitle>
                <CardDescription className="text-slate-500 font-medium">Areas where you consistently excel</CardDescription>
              </CardHeader>
              <CardContent className="pt-6">
                {strengths.length > 0 ? (
                  <ul className="space-y-4">
                    {strengths.map(([topic, data]) => (
                      <li key={topic} className="flex items-center justify-between p-4 bg-emerald-50 rounded-xl border border-emerald-100">
                        <span className="font-bold text-slate-800 capitalize">{topic}</span>
                        <Badge className="bg-emerald-100 text-emerald-700 border-none">{data.accuracy}% Accuracy</Badge>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-slate-500 text-sm italic text-center py-4">More data needed to establish definitive strengths.</p>
                )}
              </CardContent>
            </Card>

            {/* Critical Vulnerabilities */}
            <Card className="bg-white border border-slate-200 shadow-sm rounded-2xl">
              <CardHeader className="border-b border-slate-100 pb-4">
                <CardTitle className="flex items-center gap-2 text-amber-800">
                  <AlertTriangle className="h-5 w-5 text-amber-600" /> Critical Vulnerabilities
                </CardTitle>
                <CardDescription className="text-slate-500 font-medium">Priority areas requiring immediate focus</CardDescription>
              </CardHeader>
              <CardContent className="pt-6">
                {weaknesses.length > 0 ? (
                  <ul className="space-y-4">
                    {weaknesses.map(([topic, data]) => (
                      <li key={topic} className="flex flex-col p-3 bg-amber-50 rounded-xl border border-amber-100">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-bold text-slate-800 capitalize">{topic}</span>
                          <Badge className="bg-amber-100 text-amber-800 border-none">{data.accuracy}% Accuracy</Badge>
                        </div>
                        
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-slate-500 text-sm italic text-center py-4">No critical vulnerabilities detected yet!</p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Master Learning Roadmap */}
          <Card className="bg-gradient-to-br from-indigo-50 to-purple-50 border border-purple-100 shadow-md rounded-2xl overflow-hidden">
            <CardHeader className="pb-2">
              <CardTitle className="flex items-center gap-2 text-slate-900">
                <BookOpen className="h-5 w-5 text-purple-600" /> Recommended Action Plan
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <p className="text-slate-700 mb-6 font-medium leading-relaxed">
                Based on your historical data, Gemini recommends shifting your focus towards 
                <span className="font-bold text-purple-700 capitalize"> {weaknesses.length > 0 ? weaknesses[0][0] : "advanced"} scenarios </span>
                to balance your cognitive profile for upcoming corporate assessments.
              </p>
              <div className="flex flex-wrap gap-4">
                <Button onClick={() => navigate("/")} className="bg-purple-600 hover:bg-purple-700 text-white rounded-xl shadow-md">
                  Start Practice
                </Button>
                <Button variant="outline" onClick={() => navigate("/progress")} className="bg-white border-purple-200 text-purple-700 hover:bg-purple-50 rounded-xl">
                  Back to Dashboard
                </Button>
              </div>
            </CardContent>
          </Card>

        </div>
      </div>
    </div>
  )
}